name: build-and-test
on: push
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: go version

